import os

pages_dir = '/home/padoswaliaunty/projects/ecell_website/new_iic_website/app/src/pages'

pages = {
    'About.tsx': {
        'title': 'About the Ecosystem',
        'content': '''The innovation ecosystem of Jadavpur University represents an integrated framework designed to nurture creativity, research translation, entrepreneurship, technology commercialization, and industry engagement.
Through interdisciplinary collaboration among students, faculty members, researchers, alumni, industry leaders, investors, and government agencies, the University fosters an environment where innovative ideas can evolve into transformative solutions.'''
    },
    'Iic.tsx': {
        'title': "Institution's Innovation Council (IIC)",
        'content': '''Established under the Ministry of Education's Innovation Cell (MIC), the Institution's Innovation Council serves as the University's principal platform for promoting innovation, design thinking, entrepreneurship, and problem-solving.
The Council actively cultivates a culture of innovation by encouraging students and researchers to address real-world challenges through technology, creativity, and interdisciplinary collaboration.'''
    },
    'Ecell.tsx': {
        'title': 'Entrepreneurship Cell (E-Cell)',
        'content': '''Established on 20 July 2016 through a workshop held in the Salt Lake Campus of Jadavpur University, the Entrepreneurship Cell serves as the University's flagship student-driven platform for entrepreneurial development and startup engagement.
The Cell functions as a bridge between academia, industry, investors, venture capital networks, startup founders, and aspiring entrepreneurs.'''
    },
    'Ipr.tsx': {
        'title': 'Intellectual Property Rights (IPR) Cell',
        'content': '''The Intellectual Property Rights Cell safeguards and promotes the intellectual assets generated by students, faculty members, researchers, and innovators.
The Cell serves as an institutional facilitator for intellectual property creation, protection, management, and commercialization.'''
    },
    'Tinkering.tsx': {
        'title': 'Tinkering Lab',
        'content': '''The Tinkering Lab serves as a collaborative innovation hub dedicated to experimentation, rapid prototyping, and hands-on learning.
The facility enables innovators to convert conceptual ideas into practical solutions through interdisciplinary engagement and technological exploration.'''
    },
    'Startup.tsx': {
        'title': 'Startup & Incubation',
        'content': '''Jadavpur University provides an enabling environment for startup creation and entrepreneurial growth by connecting innovators with mentors, industry experts, investors, and institutional support systems.
The university has supported numerous startups and generated various incorporations and recognitions.'''
    }
}

template = """import React from 'react';

export default function {component_name}() {{
  return (
    <main className="min-h-screen bg-midnight text-pure-white pt-32 pb-24 px-6 flex flex-col items-center">
      <div className="max-w-3xl w-full">
        <h1 className="text-4xl md:text-6xl font-bold tracking-tight mb-8">{{`{title}`}}</h1>
        <div className="prose prose-invert prose-lg">
          {content_jsx}
        </div>
      </div>
    </main>
  );
}}
"""

for filename, data in pages.items():
    comp_name = filename.split('.')[0]
    content_paragraphs = "".join([f"<p className='text-gray-300 leading-relaxed mb-6'>{p}</p>" for p in data['content'].split('\n')])
    
    file_content = template.format(
        component_name=comp_name,
        title=data['title'],
        content_jsx=content_paragraphs
    )
    
    with open(os.path.join(pages_dir, filename), 'w') as f:
        f.write(file_content)

print("Created pages.")
