

export default function Ipr() {
  return (
    <main className="min-h-screen bg-midnight text-pure-white pt-32 pb-24 px-6 flex flex-col items-center">
      <div className="max-w-3xl w-full">
        <h1 className="text-4xl md:text-6xl font-bold tracking-tight mb-8">{`Intellectual Property Rights (IPR) Cell`}</h1>
        <div className="prose prose-invert prose-lg">
          <p className='text-gray-300 leading-relaxed mb-6'>The Intellectual Property Rights Cell safeguards and promotes the intellectual assets generated by students, faculty members, researchers, and innovators.</p><p className='text-gray-300 leading-relaxed mb-6'>The Cell serves as an institutional facilitator for intellectual property creation, protection, management, and commercialization.</p>
        </div>
      </div>
    </main>
  );
}
