
export default function Ipr() {
  return (
    <main className="min-h-screen bg-midnight text-pure-white pt-32 pb-24 px-6 flex flex-col items-center">
      <div className="max-w-3xl w-full">
        <p className="text-xs font-medium tracking-[0.08em] uppercase mb-4" style={{ color: 'rgba(200, 229, 88, 0.8)' }}>
          OUR INITIATIVES
        </p>
        <div className="flex flex-col md:flex-row items-start md:items-center gap-6 mb-8">
          <img src="/assets/ipr.jpg" alt="IPR Cell Logo" className="w-24 h-24 object-cover rounded-xl" />
          <h1 className="text-4xl md:text-6xl font-bold tracking-tight">{`Intellectual Property Rights (IPR) Cell`}</h1>
        </div>

        <div className="prose prose-invert prose-lg space-y-6 mb-12">
          <p className='text-gray-300 leading-relaxed'>
            The Intellectual Property Rights Cell at Jadavpur University is a unit dedicated to protecting and promoting intellectual property rights for students, faculty members, and researchers. The IPR Cell helps to identify, develop, and commercialize innovative ideas.
          </p>

          <h3 className="text-xl font-semibold">Our Mission</h3>
          <p className='text-gray-300 leading-relaxed'>
            We safeguard and promote the intellectual assets generated by our academic community while facilitating the protection and commercialization of their innovations. The Cell provides legal assistance and consultation on all forms of intellectual property rights.
          </p>

          <h3 className="text-xl font-semibold">Services Provided</h3>
          <ul className="list-disc list-inside space-y-2 text-gray-300">
            <li>Protection of copyrights, trademarks, patents, and geographical indications</li>
            <li>Guidance for plant varieties and industrial designs protection</li>
            <li>Assistance with semiconductor integrated circuit layout designs</li>
            <li>IPR Fund support for securing intellectual property rights</li>
            <li>Patent filing and legal consultation</li>
            <li>Technology licensing facilitation</li>
          </ul>

          <h3 className="text-xl font-semibold">IPR Fund Support</h3>
          <p className='text-gray-300 leading-relaxed'>
            Jadavpur University offers an IPR Fund to support its own students and faculty members in securing intellectual property rights for their innovations and creations. This initiative ensures that innovative ideas are properly protected and can be commercialized effectively.
          </p>

          <h3 className="text-xl font-semibold">IPR Policy</h3>
          <p className='text-gray-300 leading-relaxed mb-2'>
            Read the official IPR Policy of Jadavpur University:
          </p>
          <a href="https://juinnovationstartup.jdvu.ac.in/resource/doc/IP_POLICY_JU%20FINAL.pdf" target="_blank" rel="noopener noreferrer" className="inline-block text-soft-lime hover:underline mb-6">
            View IPR Policy
          </a>

          <h3 className="text-xl font-semibold">Important Documents</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-8">
            <a href="https://juinnovationstartup.jdvu.ac.in/resource/doc/Patent-Search-Forwarding-Letter.pdf" target="_blank" rel="noopener noreferrer" className="p-3 bg-white/5 border border-white/10 rounded-lg hover:bg-white/10 transition-colors text-sm">Patent Search Forwarding Letter</a>
            <a href="https://juinnovationstartup.jdvu.ac.in/resource/doc/POWER-OF-ATTORNEY.pdf" target="_blank" rel="noopener noreferrer" className="p-3 bg-white/5 border border-white/10 rounded-lg hover:bg-white/10 transition-colors text-sm">Power Of Attorney</a>
            <a href="https://juinnovationstartup.jdvu.ac.in/resource/doc/Search-Report-Template.pdf" target="_blank" rel="noopener noreferrer" className="p-3 bg-white/5 border border-white/10 rounded-lg hover:bg-white/10 transition-colors text-sm">Search Report Template</a>
            <a href="https://juinnovationstartup.jdvu.ac.in/resource/doc/Steps-for-Patent-Filing.pdf" target="_blank" rel="noopener noreferrer" className="p-3 bg-white/5 border border-white/10 rounded-lg hover:bg-white/10 transition-colors text-sm">Steps For Patent Filing</a>
            <a href="https://juinnovationstartup.jdvu.ac.in/resource/doc/ANNEXURE_I.pdf" target="_blank" rel="noopener noreferrer" className="p-3 bg-white/5 border border-white/10 rounded-lg hover:bg-white/10 transition-colors text-sm">Annexure I</a>
            <a href="https://juinnovationstartup.jdvu.ac.in/resource/doc/ANNEXURE_II.pdf" target="_blank" rel="noopener noreferrer" className="p-3 bg-white/5 border border-white/10 rounded-lg hover:bg-white/10 transition-colors text-sm">Annexure II</a>
            <a href="https://juinnovationstartup.jdvu.ac.in/resource/doc/ANNEXURE_III.pdf" target="_blank" rel="noopener noreferrer" className="p-3 bg-white/5 border border-white/10 rounded-lg hover:bg-white/10 transition-colors text-sm">Annexure III</a>
            <a href="https://juinnovationstartup.jdvu.ac.in/resource/doc/ANNEXURE_IV.pdf" target="_blank" rel="noopener noreferrer" className="p-3 bg-white/5 border border-white/10 rounded-lg hover:bg-white/10 transition-colors text-sm">Annexure IV</a>
            <a href="https://juinnovationstartup.jdvu.ac.in/resource/doc/ANNEXURE-V.pdf" target="_blank" rel="noopener noreferrer" className="p-3 bg-white/5 border border-white/10 rounded-lg hover:bg-white/10 transition-colors text-sm">Annexure V</a>
            <a href="https://juinnovationstartup.jdvu.ac.in/resource/doc/ANNEXURE-VI.pdf" target="_blank" rel="noopener noreferrer" className="p-3 bg-white/5 border border-white/10 rounded-lg hover:bg-white/10 transition-colors text-sm">Annexure VI</a>
            <a href="https://juinnovationstartup.jdvu.ac.in/resource/doc/ANNEXURE-VII.pdf" target="_blank" rel="noopener noreferrer" className="p-3 bg-white/5 border border-white/10 rounded-lg hover:bg-white/10 transition-colors text-sm">Annexure VII</a>
          </div>

          <h3 className="text-xl font-semibold">IPR Members</h3>
          <p className='text-gray-300 leading-relaxed'>
            <strong className="text-white">Convenor:</strong> Prof. Susanta Ray<br/>
            <strong className="text-white">Members:</strong> Prof. Rajib Bandyopadhyay, Prof. Swarnendu Sen, Prof. Bhaskar Gupta, Prof. Debangshu Dey, Prof. Biswendu Chatterjee, Prof. Chandreyee Chowdhury, Prof. Abhisek Roy, Prof. Sanmoy Karmakar, Prof. Paramita Bhattacharjee.
          </p>
        </div>

        <div className="flex gap-4">
          <a href="mailto:iprcellju@jadavpuruniversity.in" className="px-6 py-3 bg-white/10 hover:bg-white/20 border border-white/20 rounded-lg transition-colors">
            Contact IPR Cell
          </a>
        </div>
      </div>
    </main>
  );
}
