import { useEffect, useRef } from 'react';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { Link } from 'react-router';

gsap.registerPlugin(ScrollTrigger);

const cells = [
  {
    number: '01',
    name: "Institution's Innovation Council",
    path: '/iic',
    description: 'Promoting innovation, design thinking, entrepreneurship, and problem-solving across the university.',
  },
  {
    number: '02',
    name: 'Entrepreneurship Cell',
    path: '/ecell',
    description: 'The flagship student-driven platform for entrepreneurial development and startup engagement.',
  },
  {
    number: '03',
    name: 'Intellectual Property Rights Cell',
    path: '/ipr',
    description: 'Safeguards and promotes intellectual assets generated by students, researchers, and innovators.',
  },
  {
    number: '04',
    name: 'Tinkering Lab',
    path: '/tinkering',
    description: 'A collaborative innovation hub dedicated to experimentation, rapid prototyping, and hands-on learning.',
  },
];

export default function ProductsSection() {
  const sectionRef = useRef<HTMLElement>(null);

  useEffect(() => {
    if (!sectionRef.current) return;
    const elements = sectionRef.current.querySelectorAll('.section-animate');
    elements.forEach((el) => {
      gsap.fromTo(
        el,
        { opacity: 0, y: 20 },
        {
          opacity: 1,
          y: 0,
          duration: 0.6,
          ease: 'power2.out',
          scrollTrigger: {
            trigger: el,
            start: 'top 80%',
          },
        }
      );
    });

    return () => {
      ScrollTrigger.getAll().forEach((t) => t.kill());
    };
  }, []);

  return (
    <section ref={sectionRef} id="ecosystem" className="w-full bg-off-white py-section">
      <div className="max-w-content mx-auto px-6">
        {/* Header */}
        <div className="text-center mb-16 section-animate">
          <p
            className="text-xs font-medium tracking-[0.08em] uppercase mb-6"
            style={{ color: 'rgba(0, 0, 0, 0.4)' }}
          >
            CORE BODIES
          </p>
          <h2 className="text-section text-midnight">
            The Pillars of Our Innovation Ecosystem
          </h2>
        </div>

        {/* Product Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {cells.map((cell) => (
            <div
              key={cell.number}
              className="section-animate bg-pure-white rounded-2xl p-8 md:p-10 flex flex-col justify-between min-h-[300px] border border-border-light transition-all duration-300 hover:-translate-y-1 hover:shadow-card-hover"
            >
              <div>
                <span className="font-mono text-xs text-black mb-4 block">
                  {cell.number}
                </span>
                <h3 className="text-subsection text-midnight mb-4">{cell.name}</h3>
                <p className="text-midnight/60">{cell.description}</p>
              </div>
              <div className="mt-8">
                <Link to={cell.path} className="text-sm font-medium text-soft-lime hover:text-lime-800 transition-colors">
                  Learn More &rarr;
                </Link>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
